### PR TITLE
Do not overwrite default failure transport

### LINKED ISSUE #238: Do not overwrite default failure transport
generic-data-index-bundle/config/pimcore/messenger.yaml
```
framework:
    messenger:
        enabled: true
        failure_transport: pimcore_generic_data_index_failed

```
Should be:

```
framework:
    messenger:
        transports:
            pimcore_generic_data_index:
                dsn: "doctrine://default?queue_name=pimcore_generic_data_index_queue"
                failure_transport: pimcore_generic_data_index_failed
```

### PR DESCRIPTION
**Pull request by morgannilsson**
## Changes in this pull request
Resolves #238

### CODE REVIEW

**Comment by lukmzig** [comment]
@morgannilsson thank you, could you please post a comment with only
`I have read the CLA Document and I hereby sign the CLA`
to sign the CLA and trigger a recheck??

**Comment by morgannilsson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattamon** [comment]
recheck

**Comment by lukmzig** [comment]
@morgannilsson thank you, it seems like this did not work. I see that for the commit you used this email address
`morgan.nilsson@ateles.se`. Is this email address added to your github account? It would be necessary to do so before signing the CLA. Thank you!

**Comment by morgannilsson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by mattamon — APPROVED** [review]
Thanks! Looks good to me now!

**Pull request merged**
